### ISSUE TITLE
ImportError: cannot import name TimeDistributedMerge

### ISSUE THREAD

**Issue by iqbal-chowdhury** [mateuszmalinowski/visual_turing_test-tutorial#1]
Hi,

I was trying to run your excellent work. Meanwhile I installed all the dependencies but I got an error when I run the code snippet of 'class BlindBOW'. The code and respective output is given. Your suggestion is highly appreciated.
`#== Model definition

from keras.layers.core import Activation
from keras.layers.core import Dense
from keras.layers.core import Dropout
from keras.layers.core import TimeDistributedMerge
from keras.layers.embeddings import Embedding

from kraino.core.model_zoo import AbstractSequentialModel
from kraino.core.model_zoo import AbstractSingleAnswer
from kraino.core.model_zoo import AbstractSequentialMultiplewordAnswer
from kraino.core.model_zoo import Config
from kraino.core.keras_extensions import DropMask
from kraino.core.keras_extensions import LambdaWithMask
from kraino.core.keras_extensions import time_distributed_masked_ave

class BlindBOW(AbstractSequentialModel, AbstractSingleAnswer):
    """
    BOW Language only model that produces single word answers.
    """
    def create(self):
        self.add(Embedding(
                self._config.input_dim, 
                self._config.textual_embedding_dim, 
                mask_zero=True))
        self.add(LambdaWithMask(time_distributed_masked_ave, output_shape=[self.output_shape[2]]))
        self.add(DropMask())
        self.add(Dropout(0.5))
        self.add(Dense(self._config.output_dim))
        self.add(Activation('softmax'))`

Output Error:
`ImportError                               Traceback (most recent call last)
<ipython-input-1-cb4e5dfc43ab> in <module>()
      5 from keras.layers.core import Dense
      6 from keras.layers.core import Dropout
----> 7 from keras.layers.core import TimeDistributedMerge
      8 from keras.layers.embeddings import Embedding
      9 

ImportError: cannot import name TimeDistributedMerge
`

**Comment by mateuszmalinowski** [comment]
You need an older version of Keras.
A new version has different API.

I tested on the Keras version with the following hashtag: b587aeee1c1be3633a56b945af3e7c2c303369ca

Quickly browsing https://github.com/fchollet/keras/tree/b587aeee1c1be3633a56b945af3e7c2c303369ca reveals there is TimeDistributedMerge in the core.py. 

Please let me know if that works.

**Comment by iqbal-chowdhury** [comment]
Issue is fixed with the provided version of Keras. Thank you.

**Comment by karimkhanp** [comment]
Thanks for the code and solution. I was getting same error, and tried with Zip package available on  https://github.com/fchollet/keras/tree/b587aeee1c1be3633a56b945af3e7c2c303369ca

Installed keras using `sudo python setup.py install` But still when I run the code provided https://github.com/karimkhanp/Seq2Seq I am getting - 

```
Traceback (most recent call last):
  File "seq2seq.py", line 5, in <module>
    from model import seq2seq
  File "/home/ubuntu/Documents/karim/Data/bse/phase3/deep_learning/Seq2Seq/seq2seq/model.py", line 5, in <module>
    from keras.layers.core import Activation, RepeatVector, TimeDistributedDense, Dropout, Dense
ImportError: cannot import name TimeDistributedDense

```
