### ISSUE TITLE
Error in the code!

### ISSUE THREAD

**Issue by ghost** [mateuszmalinowski/visual_turing_test-tutorial#3]
the word2index of the answers in the notebook is wrong because wordcount is not right.
Look at the 2 keys "alarm" and "alarm,"
![screenshot from 2017-01-23 17-27-08](https://cloud.githubusercontent.com/assets/13083890/22210230/c8273e08-e191-11e6-9528-05640417f77d.png)

i think the solution is to fix this function
`frequencies(' '.join(train_raw_y).split(' '))`

we must split the answers by the ' ' and ',' NOT just ' ' alone
Am i right?

**Comment by mateuszmalinowski** [comment]
Thanks a lot! I will check this issue in the weekend. It definitely should not be the case.

**Comment by mateuszmalinowski** [comment]
Thanks for letting me know about the issue. Now I keep whole answers.
